
-- 1. TABEL DISKUSI (Untuk menyimpan tanya jawab dengan Mentor AI)
-- Hapus tabel lama jika struktur salah (OPSIONAL, HATI-HATI DATA HILANG)
-- DROP TABLE IF EXISTS lesson_discussions;

CREATE TABLE IF NOT EXISTS lesson_discussions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_day INTEGER NOT NULL,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  user_name TEXT, -- Kolom PENTING agar nama user muncul di chat
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Policy agar tabel bisa dibaca/tulis publik (karena app ini tanpa auth login)
ALTER TABLE lesson_discussions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public insert discussions" ON lesson_discussions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select discussions" ON lesson_discussions FOR SELECT USING (true);


-- 2. TABEL LEADERBOARD (Untuk menyimpan skor ujian)
CREATE TABLE IF NOT EXISTS exam_leaderboard (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  score INTEGER NOT NULL,
  date TIMESTAMPTZ DEFAULT NOW()
);

-- Policy leaderboard
ALTER TABLE exam_leaderboard ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public insert leaderboard" ON exam_leaderboard FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select leaderboard" ON exam_leaderboard FOR SELECT USING (true);


-- 3. BUCKET STORAGE (Untuk menyimpan gambar hasil generate AI)
-- Note: Bucket biasanya dibuat lewat UI Storage, tapi ini script untuk policy-nya
-- Pastikan Anda membuat bucket bernama 'images' dan set Public.
-- INSERT INTO storage.buckets (id, name, public) VALUES ('images', 'images', true);
