

export enum Difficulty {
  BEGINNER = 'Pemula',
  INTERMEDIATE = 'Menengah',
  ADVANCED = 'Mahir'
}

export interface Lesson {
  day: number;
  title: string;
  category: 'Mindset' | 'Technical' | 'Fundamental' | 'Bandarmologi' | 'Risk Management';
  description: string;
  keyPoints: string[];
  isCompleted: boolean;
  content?: string; // Content generated by AI
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: Date;
  isError?: boolean;
}

export type ViewState = 'dashboard' | 'curriculum' | 'lesson' | 'mentor' | 'tools' | 'exam' | 'leaderboard' | 'products' | 'profile';

export interface UserProgress {
  completedDays: number[];
  currentDay: number;
  streak: number;
  examScore?: number;
  examDate?: string;
  passedExam?: boolean;
  username?: string; // Nama user untuk leaderboard
}

export interface ExamQuestion {
  id: number;
  question: string;
  options: string[];
  correctAnswer: number; // Index 0-3
  category: string;
}

export interface LeaderboardEntry {
  name: string;
  score: number;
  date: string;
  rank?: number;
}

export interface TradeLog {
  id: string;
  stockCode: string;
  buyDate: string;
  buyPrice: number;
  sellPrice?: number;
  lots: number;
  status: 'OPEN' | 'CLOSED' | 'WIN' | 'LOSS';
  notes: string;
  pnl?: number; // Profit and Loss value
  pnlPercent?: number;
}

export interface GlossaryTerm {
  term: string;
  definition: string;
  category: 'General' | 'Technical' | 'Bandarmologi';
}