
import React, { useState, useEffect } from 'react';
import { Lesson } from '../types';
import { getLessonContent, generateLessonImage } from '../services/geminiService';
import { ArrowLeft, CheckCircle, BookOpen, Quote, Info, Sparkles, Loader2, RefreshCw, Image as ImageIcon } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import LessonDiscussion from './LessonDiscussion';

interface LessonViewProps {
  lesson: Lesson;
  onBack: () => void;
  onComplete: (day: number) => void;
  userName: string;
}

// Komponen Gambar Otomatis yang sekarang menggunakan Supabase via Service
const AutoGeneratedImage = ({ src, alt, lessonDay, ...props }: any) => {
  const [currentSrc, setCurrentSrc] = useState<string | null>(null);
  const [status, setStatus] = useState<'idle' | 'loading' | 'loaded' | 'error'>('idle');
  
  const isVisualPlaceholder = alt?.startsWith('Visual:');
  const visualDescription = alt?.replace('Visual:', '').trim();

  useEffect(() => {
    if (!isVisualPlaceholder) {
      setCurrentSrc(src);
      setStatus('loaded');
      return;
    }

    // Panggil service (Service akan cek Supabase dulu)
    handleAutoGenerate();
  }, [lessonDay, src, isVisualPlaceholder]);

  const handleAutoGenerate = async () => {
    setStatus('loading');
    try {
      // Kita pass lessonDay agar service bisa cek file 'lesson-day-X.png' di Supabase
      const result = await generateLessonImage(visualDescription, lessonDay);
      if (result) {
        setCurrentSrc(result);
        setStatus('loaded');
      } else {
        setStatus('error');
      }
    } catch (e) {
      console.error("Gagal memuat gambar", e);
      setStatus('error');
    }
  };

  const handleRegenerate = (e: React.MouseEvent) => {
    e.stopPropagation();
    handleAutoGenerate(); 
  };

  // Render untuk gambar biasa
  if (!isVisualPlaceholder) {
    return (
       <div className="rounded-xl overflow-hidden shadow-lg border border-slate-200 my-8 w-full">
         <img src={src} alt={alt} className="w-full h-auto object-cover" {...props} />
       </div>
    );
  }

  // Render Status Loading
  if (status === 'loading') {
    return (
      <figure className="my-6 md:my-10 w-full">
        <div className="rounded-2xl overflow-hidden border border-blue-100 bg-blue-50/50 relative h-[200px] md:h-[300px] flex flex-col items-center justify-center animate-pulse w-full">
           <div className="absolute inset-0 bg-gradient-to-r from-blue-50 via-white to-blue-50 opacity-50"></div>
           <Loader2 className="w-8 h-8 md:w-10 md:h-10 text-blue-500 animate-spin mb-4 relative z-10" />
           <p className="text-blue-600 font-medium relative z-10 text-xs md:text-base px-4 text-center">Sedang menggambar visual...</p>
        </div>
      </figure>
    );
  }

  // Render Status Error
  if (status === 'error') {
     return (
      <figure className="my-6 md:my-10 relative group w-full">
        <div className="rounded-2xl overflow-hidden border border-red-100 bg-red-50 h-[200px] flex flex-col items-center justify-center w-full">
           <ImageIcon className="w-8 h-8 md:w-10 md:h-10 text-red-300 mb-2" />
           <p className="text-red-500 font-medium text-xs md:text-sm">Gagal memuat visual</p>
           <button 
             onClick={handleRegenerate}
             className="mt-3 px-4 py-2 bg-white text-red-500 border border-red-200 rounded-full text-xs md:text-sm hover:bg-red-50 transition-colors"
           >
             Coba Lagi
           </button>
        </div>
      </figure>
     );
  }

  // Render Sukses
  return (
    <figure className="my-6 md:my-10 relative group w-full">
      <div className="rounded-2xl overflow-hidden shadow-xl border border-slate-200 bg-slate-50 relative min-h-[200px] md:min-h-[300px] flex items-center justify-center w-full">
        <img 
          src={currentSrc || src} 
          alt={alt} 
          className="w-full h-auto object-cover max-h-[500px]"
          {...props} 
        />
        
        {/* Badge Cloud/AI */}
        <div className="absolute bottom-4 right-4 bg-black/60 text-white text-[10px] font-bold px-2 py-1 rounded-md backdrop-blur-md border border-white/10 flex items-center shadow-sm opacity-60 group-hover:opacity-100 transition-opacity">
           <Sparkles className="w-3 h-3 mr-1 text-yellow-400" /> Visual by AI
        </div>
      </div>

      {alt && (
        <figcaption className="text-center text-xs md:text-sm text-slate-500 mt-3 italic flex items-center justify-center bg-slate-50 py-2 rounded-lg border border-slate-100 mx-auto max-w-full md:max-w-2xl px-3 break-words">
          <Info className="w-3 h-3 mr-2 text-blue-400 flex-shrink-0" />
          <span className="truncate max-w-[200px] md:max-w-full">{visualDescription}</span>
        </figcaption>
      )}
    </figure>
  );
};

const LessonView: React.FC<LessonViewProps> = ({ lesson, onBack, onComplete, userName }) => {
  const content = getLessonContent(lesson);

  const markdownComponents = {
    // HEADING
    h1: ({node, ...props}: any) => <h1 className="text-2xl md:text-4xl font-extrabold text-slate-900 mt-6 md:mt-8 mb-4 pb-2 md:pb-4 border-b border-slate-100 bg-clip-text text-transparent bg-gradient-to-r from-slate-900 to-slate-700 leading-tight break-words" {...props} />,
    h2: ({node, children, ...props}: any) => (
      <h2 className="text-lg md:text-2xl font-bold text-slate-800 mt-6 md:mt-8 mb-3 flex items-start leading-snug break-words" {...props}>
        <span className="w-1 h-5 md:w-1.5 md:h-8 bg-blue-500 mr-2 md:mr-3 rounded-full flex-shrink-0 mt-1 md:mt-0"></span>
        <span className="flex-1">{children}</span>
      </h2>
    ),
    h3: ({node, ...props}: any) => <h3 className="text-base md:text-xl font-bold text-slate-800 mt-5 md:mt-6 mb-2 break-words" {...props} />,
    
    // TEXT BODY
    p: ({node, ...props}: any) => <p className="text-slate-600 leading-relaxed mb-4 text-[15px] md:text-lg tracking-normal md:tracking-wide break-words text-justify md:text-left" {...props} />,
    
    // LISTS
    ul: ({node, ...props}: any) => <ul className="list-none mb-6 space-y-2 md:space-y-3 text-slate-600 text-[15px] md:text-lg" {...props} />,
    ol: ({node, ...props}: any) => <ol className="list-decimal list-outside ml-4 md:ml-6 mb-6 space-y-2 md:space-y-3 text-slate-600 text-[15px] md:text-lg font-medium pl-1" {...props} />,
    li: ({node, children, ...props}: any) => (
      <li className="flex items-start" {...props}>
        {/* Bullet custom hanya untuk UL, OL pakai default number */}
        {props.ordered ? (
             <span className="break-words">{children}</span>
        ) : (
            <>
                <span className="mr-2 md:mr-3 mt-2 md:mt-2.5 w-1.5 h-1.5 bg-blue-400 rounded-full flex-shrink-0 block"></span>
                <div className="flex-1 break-words">{children}</div>
            </>
        )}
      </li>
    ),

    // QUOTE
    blockquote: ({node, ...props}: any) => (
      <div className="relative bg-gradient-to-r from-blue-50 to-indigo-50 p-4 md:p-6 my-6 md:my-8 rounded-2xl italic text-slate-700 shadow-sm border border-blue-100 text-sm md:text-base">
        <Quote className="absolute top-4 left-4 w-5 h-5 md:w-8 md:h-8 text-blue-200/50 transform -scale-x-100" />
        <div className="relative z-10 pl-3 md:pl-4 border-l-4 border-blue-400 break-words" {...props} />
      </div>
    ),

    // IMAGES & MEDIA
    img: (props: any) => <AutoGeneratedImage {...props} lessonDay={lesson.day} />, 
    
    // CODE
    code: ({node, inline, ...props}: any) => (
        inline ? (
            <code className="bg-slate-100 text-pink-600 px-1.5 py-0.5 rounded text-[13px] md:text-sm font-mono font-bold border border-slate-200 break-words" {...props} />
        ) : (
            <div className="w-full overflow-x-auto my-4 rounded-lg border border-slate-200">
                <pre className="bg-slate-900 text-slate-50 p-4 text-xs md:text-sm font-mono block min-w-full">
                    <code {...props} />
                </pre>
            </div>
        )
    ),
    
    // BOLD
    strong: ({node, ...props}: any) => <strong className="font-bold text-slate-900 bg-yellow-100/50 px-0.5 rounded break-words" {...props} />,

    // TABLES (Critical for Mobile)
    table: ({node, ...props}: any) => (
        <div className="w-full overflow-x-auto my-6 rounded-xl border border-slate-200 shadow-sm">
            <table className="w-full text-sm text-left text-slate-600 min-w-[500px]" {...props} />
        </div>
    ),
    thead: ({node, ...props}: any) => <thead className="text-xs text-slate-700 uppercase bg-slate-50 border-b border-slate-200" {...props} />,
    tbody: ({node, ...props}: any) => <tbody className="divide-y divide-slate-100" {...props} />,
    tr: ({node, ...props}: any) => <tr className="bg-white hover:bg-slate-50" {...props} />,
    th: ({node, ...props}: any) => <th className="px-4 py-3 font-bold whitespace-nowrap" {...props} />,
    td: ({node, ...props}: any) => <td className="px-4 py-3 break-words" {...props} />,
  };

  return (
    <div className="max-w-4xl mx-auto pb-24 md:pb-20">
      {/* Navigation Header */}
      <div className="sticky top-0 md:top-0 z-40 bg-white/95 backdrop-blur-xl border-b border-slate-200 px-4 py-3 mb-6 md:mb-8 -mx-4 md:mx-0 md:rounded-b-2xl shadow-sm transition-all flex justify-between items-center gap-2">
        <button 
          onClick={onBack}
          className="group flex items-center text-slate-600 hover:text-blue-600 transition-colors font-medium p-1"
        >
          <div className="bg-slate-100 p-2 rounded-full md:mr-3 group-hover:bg-blue-100 transition-colors">
             <ArrowLeft className="w-5 h-5" />
          </div>
          <span className="hidden md:inline">Kembali</span>
        </button>
        
        <div className="flex items-center gap-2 md:gap-3">
          <div className="text-[10px] md:text-xs font-bold text-slate-400 uppercase tracking-widest border border-slate-200 px-2 md:px-3 py-1.5 rounded-full bg-slate-50 whitespace-nowrap">
            Day {lesson.day}
          </div>
          
          <button
            onClick={() => onComplete(lesson.day)}
            disabled={lesson.isCompleted}
            className={`
              flex items-center px-3 py-2 md:px-4 md:py-2 rounded-full text-xs md:text-sm font-bold transition-all shadow-sm transform active:scale-95 whitespace-nowrap
              ${lesson.isCompleted
                ? 'bg-green-100 text-green-700 border border-green-200 cursor-default'
                : 'bg-blue-600 text-white hover:bg-blue-700 hover:shadow-md'
              }
            `}
          >
            {lesson.isCompleted ? (
              <>
                <CheckCircle className="w-4 h-4 mr-1.5" />
                <span>Selesai</span>
              </>
            ) : (
              <>
                <span>Selesai</span>
                <CheckCircle className="w-4 h-4 ml-1.5" />
              </>
            )}
          </button>
        </div>
      </div>

      <div className="bg-white rounded-2xl md:rounded-[2rem] shadow-lg md:shadow-2xl shadow-slate-200/50 border border-white overflow-hidden ring-1 ring-slate-100">
        {/* Decorative Header Image Area */}
        <div className="h-48 md:h-64 bg-gradient-to-br from-slate-900 via-indigo-900 to-slate-900 relative overflow-hidden">
           <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-10 mix-blend-overlay"></div>
           {/* Abstract Shapes */}
           <div className="absolute -top-24 -right-24 w-64 h-64 bg-blue-500 rounded-full blur-[100px] opacity-30"></div>
           <div className="absolute -bottom-24 -left-24 w-64 h-64 bg-purple-500 rounded-full blur-[100px] opacity-30"></div>
           
           <div className="absolute bottom-0 left-0 w-full h-32 bg-gradient-to-t from-white to-transparent"></div>
           
           <div className="absolute bottom-6 left-4 right-4 md:bottom-10 md:left-12 md:right-12">
              <span className="inline-flex items-center px-3 py-1 md:px-4 md:py-1.5 rounded-full bg-white/10 backdrop-blur-md text-white text-[10px] md:text-xs font-bold mb-3 border border-white/20 shadow-lg">
                <BookOpen className="w-3 h-3 mr-2" />
                {lesson.category}
              </span>
              <h1 className="text-2xl md:text-5xl font-black text-white leading-tight drop-shadow-md tracking-tight mb-2 break-words">
                {lesson.title}
              </h1>
           </div>
        </div>

        {/* Main Content */}
        <div className="px-5 py-4 md:px-12 md:py-8">
           <div className="flex items-start mb-6 md:mb-10 bg-slate-50 p-4 md:p-6 rounded-2xl border border-slate-100">
              <Info className="w-5 h-5 md:w-6 md:h-6 text-blue-500 mr-3 mt-1 flex-shrink-0" />
              <p className="text-[15px] md:text-lg text-slate-600 italic font-medium leading-relaxed break-words">
                "{lesson.description}"
              </p>
           </div>

            {/* Content Article with Prose Plugin Class for better typography */}
            <article className="prose prose-slate prose-lg max-w-none prose-p:text-slate-600 prose-headings:text-slate-800 prose-a:text-blue-600">
              {/* @ts-ignore */}
              <ReactMarkdown components={markdownComponents}>
                {content}
              </ReactMarkdown>
            </article>

            {/* DISCUSSION SECTION */}
            <LessonDiscussion lessonDay={lesson.day} lessonTitle={lesson.title} userName={userName} />
        </div>
      </div>
    </div>
  );
};

export default LessonView;
